import { createRepository } from './repository.js';
import { directions, operationLabels, DEMO_DATE } from './seed.js';
import { metrics, payroll, trend, matches, periodRows, sum, escapeHtml as e, csvCell, range } from './domain.js';
import { icon } from './icons.js';
const config=window.CRM_CONFIG||{dataMode:'demo',apiBaseUrl:'/api/v1'},repo=createRepository(config);
const app=document.querySelector('#app'),overlay=document.querySelector('#overlay');
let state,filters={direction:'all',period:'today'},search='',receiptFilter='all',financeTab='result',messages=[],busy=false,lastFocus;
const pages={overview:['Обзор склада','dashboard'],inventory:['Товары и остатки','box'],receiving:['Приёмка','receive'],places:['Грузовые места','move'],team:['Команда и зарплата','team'],finance:['Финансы','wallet'],planning:['Планирование','chart'],assistant:['ИИ-помощник','spark'],settings:['Настройки','settings']};
const route=()=>location.hash.replace(/^#\/?/,'')||'overview';
const n=v=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(v);
const money=v=>n(v)+' ₽';
const shortMoney=v=>n(v/1000)+' тыс. ₽';
const d=v=>new Date(v+'T00:00:00').toLocaleDateString('ru-RU',{day:'numeric',month:'short'});
const initials=name=>name.split(' ').map(x=>x[0]).slice(0,2).join('');
const directionOptions=(value='all',all=true)=>(all?'<option value="all">Все направления</option>':'')+Object.entries(directions).map(([k,v])=>`<option value="${k}" ${k===value?'selected':''}>${e(v)}</option>`).join('');
const filtered=rows=>rows.filter(x=>matches(x,filters.direction));
const empty=(text='По выбранным условиям ничего не найдено')=>`<div class="empty">${e(text)}</div>`;
const badge=(status)=>`<span class="status ${status}">${({waiting:'Ожидает приёмки',accepted:'Принято',discrepancy:'Расхождение',stored:'На хранении','awaiting-placement':'К размещению'})[status]||e(status)}</span>`;
function title(text,subtitle,actions=''){return `<div class="page-heading"><div><h1>${text}</h1><p>${subtitle}</p></div><div class="heading-actions">${actions}</div></div>`;}
const button=(text,action,ico,primary=false)=>`<button class="btn ${primary?'primary':''}" data-action="${action}">${ico?icon(ico):''}${text}</button>`;
function controls(period=true){return `<div class="filters"><div class="filter-left"><label class="select-wrap"><span class="sr-only" hidden>Направление</span><select id="direction" aria-label="Направление">${directionOptions(filters.direction)}</select></label>${period?`<div class="segments" aria-label="Период"><button data-period="today" class="${filters.period==='today'?'active':''}" aria-pressed="${filters.period==='today'}">День</button><button data-period="week" class="${filters.period==='week'?'active':''}" aria-pressed="${filters.period==='week'}">7 дней</button></div>`:''}</div><span class="date-label">${icon('calendar')}${period?(filters.period==='today'?'3 октября 2026':'27 сентября — 3 октября 2026'):'Остатки на 3 октября 2026'} · демо-период</span></div>`;}
function kpi(label,value,current,previous,ico,target,featured=false,good=true){const t=trend(current,previous,good);return `<a class="kpi ${featured?'featured':''}" href="#/${target}"><span class="kpi-label">${label}<span class="kpi-icon">${icon(ico)}</span></span><strong class="kpi-value">${value}</strong><span class="kpi-bottom"><span class="trend ${t.tone}">${t.text}</span><span>к предыдущему ${filters.period==='today'?'дню':'периоду'}</span></span></a>`;}
function table(headers,rows){return rows.length?`<div class="table-scroll"><table class="data-table"><thead><tr>${headers.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.map(cells=>`<tr>${cells.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:empty();}
function panel(head,body,extra=''){return `<section class="panel"><div class="panel-head"><h2>${head}</h2>${extra}</div>${body}</section>`;}
function chart(){
 const dates=filters.period==='today'?['2026-10-03']:Array.from({length:7},(_,i)=>new Date(Date.UTC(2026,8,27+i)).toISOString().slice(0,10));
 const values=dates.map(date=>{const ops=filtered(state.operations).filter(x=>x.date===date&&x.confirmed);return {date,receive:sum(ops.filter(x=>x.type==='receive'),'quantity'),ship:sum(ops.filter(x=>x.type==='ship'),'quantity')};});
 const max=Math.max(1,...values.flatMap(x=>[x.receive,x.ship]))*1.2,w=620,h=210,left=44,right=10,base=173,plot=146,group=(w-left-right)/values.length,bw=Math.min(27,group*.25);
 let svg='';for(let i=0;i<4;i++){const y=base-plot*i/3;svg+=`<line x1="${left}" x2="${w-right}" y1="${y}" y2="${y}"/><text x="${left-8}" y="${y+4}" text-anchor="end">${n(max*i/3)}</text>`;}
 values.forEach((x,i)=>{const cx=left+group*(i+.5);for(const [j,key]of ['receive','ship'].entries()){const bh=x[key]/max*plot;svg+=`<rect x="${cx+(j===0?-bw-3:3)}" y="${base-bh}" width="${bw}" height="${bh}" rx="4" fill="${j===0?'#407554':'#c7dda9'}"><title>${d(x.date)} · ${j===0?'Принято':'Отгружено'}: ${n(x[key])} шт.</title></rect>`;}svg+=`<text x="${cx}" y="198" text-anchor="middle">${d(x.date)}</text>`;});
 return `<div class="panel-body"><svg class="chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="${e(values.map(x=>`${d(x.date)}: принято ${x.receive}, отгружено ${x.ship}`).join('; '))}">${svg}</svg></div><div class="chart-foot">Подтверждённые единицы в операциях приёмки и отгрузки</div>`;
}
function overview(){
 const m=metrics(state,filters),p=metrics(state,filters,true),waiting=filtered(state.receipts).filter(r=>r.status==='waiting'),bad=sum(filtered(state.products),'quarantine'),debt=filtered(state.debts).filter(x=>x.kind==='receivable'&&x.due<DEMO_DATE);
 const latest=filtered(state.receipts).slice(0,3).map(r=>[`<strong>${e(r.id)}</strong><small>${e(r.owner)}</small>`,n(r.expected)+' шт.',badge(r.status),`<a class="row-action" href="#/receiving">Открыть</a>`]);
 const zones=state.zones.filter(z=>filters.direction==='all'||z.direction===filters.direction);
 return title('Обзор склада','Всё, что важно для работы склада сегодня',button('Экспорт отчёта','export','download')+`<a class="btn primary" href="#/receiving">${icon('plus')}Приёмка</a>`)+controls()+
 `<div class="kpi-grid">${kpi('Начислено клиентам',money(m.revenue),m.revenue,p.revenue,'wallet','finance',true)}${kpi('Обработано, операций',n(m.operations),m.operations,p.operations,'box','team')}${kpi('Начислено команде',money(m.payroll),m.payroll,p.payroll,'team','team',false,false)}${kpi('Управленческий результат',money(m.profit),m.profit,p.profit,'chart','finance')}</div>
 <div class="dashboard-middle">${panel('Движение товаров',chart(),'<div class="legend"><span><i class="dot"></i>Приёмка</span><span><i class="dot light"></i>Отгрузка</span></div>')}
 ${panel('Требуют внимания',`<div class="alert-list"><a class="alert-item" href="#/receiving"><span class="alert-icon">${icon('clock')}</span><div><strong>${waiting.length} поступления в очереди</strong><p>${n(sum(waiting,'expected'))} шт. заявлено · ${sum(waiting,'places')} грузовых мест</p></div><span class="chevron">${icon('chevron')}</span></a><a class="alert-item" href="#/inventory"><span class="alert-icon red">${icon('alert')}</span><div><strong>${n(bad)} шт. на проверке</strong><p>Выделены из доступного остатка</p></div><span class="chevron">${icon('chevron')}</span></a><a class="alert-item" href="#/finance"><span class="alert-icon blue">${icon('wallet')}</span><div><strong>${money(sum(debt))} просрочено</strong><p>Задолженность клиентов на 3 октября</p></div><span class="chevron">${icon('chevron')}</span></a></div>`,'<span class="count-badge">Контроль</span>')}</div>
 <div class="bottom-grid">${panel('Последние поступления',`<div class="space-top">${table(['Документ / владелец','Заявлено','Статус',''],latest)}</div>`,'<a class="link" href="#/receiving">Все поступления</a>')}
 ${panel('Загрузка склада',`<div class="panel-body">${zones.map(z=>`<div class="zone"><div class="zone-row"><span>${e(z.name)}</span><span>${Math.round(z.used/z.area*100)}%</span></div><div class="progress" role="meter" aria-label="${e(z.name)}" aria-valuenow="${z.used}" aria-valuemin="0" aria-valuemax="${z.area}"><span style="width:${z.used/z.area*100}%"></span></div></div>`).join('')}<div class="zone-summary"><span>Используется / площадь</span><strong>${n(sum(zones,'used'))} / ${n(sum(zones,'area'))} м²</strong></div></div>`)} </div>`;
}
function inventory(){const products=filtered(state.products).filter(p=>[p.sku,p.name,p.owner,p.color].join(' ').toLowerCase().includes(search.toLowerCase()));
 return title('Товары и остатки','Остатки по владельцам, резервам и состоянию',button('Экспорт CSV','inventory-export','download'))+controls(false)+`<div class="summary-strip"><div><span>На складе</span><strong>${n(sum(filtered(state.products),'onHand'))} шт.</strong></div><div><span>Зарезервировано</span><strong>${n(sum(filtered(state.products),'reserved'))} шт.</strong></div><div><span>На проверке</span><strong>${n(sum(filtered(state.products),'quarantine'))} шт.</strong></div><div><span>Доступно</span><strong>${n(filtered(state.products).reduce((a,p)=>a+p.onHand-p.reserved-p.quarantine,0))} шт.</strong></div></div><section class="panel"><div class="table-toolbar"><label class="search">${icon('search')}<input id="search" aria-label="Поиск товара" placeholder="Артикул, название или владелец" value="${e(search)}"></label><span class="toolbar-note">${products.length} позиций · размеры и цвета отдельно</span></div><div id="search-results">${inventoryTable(products)}</div></section>`;
}
function inventoryTable(products){return table(['Товар / артикул','Владелец','На складе','Резерв','Проверка','Доступно'],products.map(p=>[`<strong>${e(p.name)}</strong><small>${e(p.sku)} · ${e(p.color)} · ${e(p.size)}</small>`,e(p.owner),n(p.onHand),n(p.reserved),p.quarantine?`<span class="status waiting">${p.quarantine}</span>`:'—',`<strong>${n(p.onHand-p.reserved-p.quarantine)}</strong>`]));}
function receiving(){const rows=filtered(state.receipts).filter(r=>receiptFilter==='all'||(receiptFilter==='waiting'?r.status==='waiting':r.status!=='waiting'));
 return title('Приёмка','От физического прибытия до подтверждённого остатка')+controls(false)+`<div class="notice">В демо можно принять поступление: остаток и выработка сотрудника обновятся в этом браузере. Все количества и имена — тестовые.</div><div class="filters"><div class="segments"><button data-receipt="all" class="${receiptFilter==='all'?'active':''}">Все</button><button data-receipt="waiting" class="${receiptFilter==='waiting'?'active':''}">Ожидают</button><button data-receipt="done" class="${receiptFilter==='done'?'active':''}">Приняты</button></div></div><div class="receipt-grid">${rows.map(r=>{const p=state.products.find(x=>x.id===r.productId);return `<article class="receipt-card"><div class="receipt-top"><strong>${e(r.id)}</strong>${badge(r.status)}</div><h3>${e(r.owner)}</h3><p>${e(p.name)} · ${e(p.sku)}</p><div class="receipt-stats"><div><strong>${n(r.expected)}</strong><span>шт. заявлено</span></div><div><strong>${r.places}</strong><span>грузовых мест</span></div>${r.actual!==undefined?`<div><strong>${n(r.actual)}</strong><span>шт. принято</span></div>`:''}</div><div class="receipt-bottom"><small>Прибыло ${new Date(r.arrived).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit',timeZone:'Europe/Moscow'})} · 3 окт.</small>${r.status==='waiting'?`<button class="btn small primary" data-receive="${e(r.id)}">Начать приёмку</button>`:`<a class="link" href="#/places">Грузовое место</a>`}</div>${r.status==='discrepancy'?`<p class="space-top">Расхождение: ${r.actual-r.expected>0?'+':''}${r.actual-r.expected} шт. Фактическое количество включено в остаток.</p>`:''}</article>`;}).join('')||empty()}</div>`;
}
function places(){const rows=filtered(state.places);return title('Грузовые места','Адрес хранения и история каждого перемещения')+controls(false)+`<div class="notice">Показан демонстрационный набор грузовых мест, а не полная адресная раскладка всех остатков.</div><section class="panel">${table(['Грузовое место','Содержимое','Владелец','Ячейка','Статус',''],rows.map(p=>[`<strong>${e(p.id)}</strong>`,`${e(state.products.find(x=>x.id===p.productId)?.name)}<small>${n(p.quantity)} шт.</small>`,e(p.owner),`<strong>${e(p.location)}</strong>`,badge(p.status),`<button class="row-action" data-place="${e(p.id)}">Открыть</button>`]))}</section>`;}
function team(){const rows=payroll(state,filters);return title('Команда и зарплата','Подтверждённые операции и предварительные начисления',button('Экспорт CSV','team-export','download'))+controls()+`<div class="summary-strip"><div><span>Сотрудников</span><strong>${rows.length}</strong></div><div><span>Базовая оплата</span><strong>${money(sum(rows,'base'))}</strong></div><div><span>Сдельная часть</span><strong>${money(sum(rows,'piece'))}</strong></div><div><span>Всего начислено</span><strong>${money(sum(rows,'total'))}</strong></div></div><section class="panel">${table(['Сотрудник','Направление','Операции, ед.','Часы','Сдельно','Всего',''],rows.map(p=>[`<div class="employee-cell"><span class="avatar">${initials(p.name)}</span><div><strong>${e(p.name)}</strong><small>${e(p.role)}</small></div></div>`,directions[p.direction],n(p.quantity),n(p.hours),money(p.piece),`<strong>${money(p.total)}</strong>`,`<button class="row-action" data-employee="${p.id}">Расчёт</button>`]))}</section><p class="sublabel">Демо-тарифы: база 800 ₽ за смену + 4 ₽ за единицу для Сталь Мастер / 2 ₽ для остальных направлений. Реальные тарифы ещё не согласованы.</p>`;}
function finance(){const m=metrics(state,filters),p=metrics(state,filters,true),expenses=periodRows(state.finance,filters).filter(x=>x.kind==='expense'),debts=filtered(state.debts);return title('Финансы','Начисления, расходы и обязательства склада',button('Добавить расход','expense','plus',true))+controls()+`<div class="kpi-grid">${kpi('Начислено клиентам',money(m.revenue),m.revenue,p.revenue,'wallet','finance',true)}${kpi('Расходы с зарплатой',money(m.expenses),m.expenses,p.expenses,'chart','finance',false,false)}${kpi('Результат',money(m.profit),m.profit,p.profit,'chart','finance')}${kpi('Начислено команде',money(m.payroll),m.payroll,p.payroll,'team','team',false,false)}</div><div class="split">${panel('Структура расходов',`<div class="panel-body">${[...new Set(expenses.map(x=>x.category))].map(c=>`<div class="finance-row"><span>${e(c)}</span><strong>${money(sum(expenses.filter(x=>x.category===c)))}</strong></div>`).join('')}<div class="finance-row"><span>Начисления сотрудникам</span><strong>${money(m.payroll)}</strong></div><div class="finance-row total"><span>Всего расходов</span><span>${money(m.expenses)}</span></div></div>`)}${panel('Расчёты с контрагентами',`<div class="panel-body">${debts.map(x=>`<div class="debt"><div class="debt-top"><span>${e(x.party)}</span><span>${money(x.amount)}</span></div><p>${x.kind==='receivable'?'Должны нам':'К оплате'} · ${e(x.description)}</p><p class="${x.due<DEMO_DATE?'overdue':''}">${x.due<DEMO_DATE?'Просрочено':'Срок'}: ${d(x.due)} 2026</p></div>`).join('')||empty('Нет обязательств для этого направления')}<p class="sublabel">Состояние на 3 октября. Оплаты отдельно от расходов.</p></div>`)}</div><section class="panel space-top"><div class="panel-head"><h2>Журнал расходов</h2><span class="toolbar-note">Последние 12 записей периода</span></div><div class="space-top">${table(['Дата','Статья','Направление','Основание','Сумма'],expenses.slice(-12).reverse().map(x=>[d(x.date),e(x.category),directions[x.direction],e(x.description),`<strong>${money(x.amount)}</strong>`]))}</div></section><p class="sublabel">Управленческая демо-модель. Налоги, взносы, амортизация и банковские оплаты пока не подключены; результат не является бухгалтерской прибылью.</p>`;}
function planning(){return title('Планирование','Потребность в пополнении и развитии склада')+`<div class="notice">Прогноз закупок появится после подключения продаж, возвратов и сроков поставки. Сейчас можно проверить логику на собственных значениях.</div><div class="split"><section class="panel"><div class="panel-head"><h2>Калькулятор пополнения</h2></div><form id="forecast-form" class="panel-body"><label class="field">Спрос, шт. в день<input name="demand" type="number" min="0" step="0.1" value="40" required></label><label class="field">Срок пополнения, дней<input name="days" type="number" min="1" step="1" value="14" required></label><label class="field">Страховой запас, шт.<input name="buffer" type="number" min="0" step="1" value="100" required></label><label class="field">Доступный остаток, шт.<input name="stock" type="number" min="0" step="1" value="320" required></label><label class="field">Поступит вовремя, шт.<input name="incoming" type="number" min="0" step="1" value="80" required></label><button class="btn primary" type="submit">Рассчитать потребность</button><div id="forecast-result" role="status" class="space-top"></div></form></section>${panel('Что потребуется для прогноза',`<div class="panel-body"><div class="finance-row">Продажи, выкупы и возвраты</div><div class="finance-row">Размеры, цвета и владельцы</div><div class="finance-row">Сезонность зимнего текстиля</div><div class="finance-row">Сроки и минимальные партии</div><div class="finance-row">Периоды отсутствия товара</div><p class="sublabel">Калькулятор иллюстрирует базовую формулу. Он не оценивает реальный спрос и не создаёт заказ.</p></div>`)}</div>`;}
function assistant(){return title('ИИ-помощник','Разбор показателей и поддержка решений')+controls()+`<div class="notice">Claude ещё не подключён. Здесь работает локальный демо-разбор трёх тем: приёмка, зарплата и финансы. Запросы не отправляются внешним сервисам.</div><div class="chat-layout"><section class="chat"><div class="chat-messages" id="messages"><div class="message"><span class="by">Демо-помощник</span>Выберите тему или спросите о приёмке, зарплате или финансовом результате. Я покажу расчёт по текущим фильтрам.</div>${messages.map(m=>`<div class="message ${m.role}">${m.role!=='user'?'<span class="by">Демо-разбор · локальные данные</span>':''}${e(m.text)}</div>`).join('')}</div><form class="chat-input" id="chat-form"><input name="message" maxlength="1000" aria-label="Сообщение помощнику" placeholder="Что требует внимания на складе?" required><button class="btn primary" type="submit" aria-label="Отправить сообщение">${icon('send')}<span>Отправить</span></button></form></section><aside>${panel('Быстрый разбор',`<div class="panel-body suggestions"><button class="suggestion" data-prompt="Что ожидает приёмки?">Что ожидает приёмки?</button><button class="suggestion" data-prompt="Как рассчитана зарплата?">Как рассчитана зарплата?</button><button class="suggestion" data-prompt="Какой финансовый результат?">Какой финансовый результат?</button></div>`)}<p class="sublabel">В серверной версии Claude получит доступ к разрешённым отчётам с учётом роли пользователя. Ключ хранится только на сервере.</p></aside></div>`;}
function settings(){return title('Настройки','Источники данных и состояние приложения')+`<div class="settings-grid"><article class="setting">${icon('server')}<h2>Источники данных</h2><p>Интеграции находятся на этапе проектирования. Дата демо-среза: 3 октября 2026 года.</p><div class="finance-row"><span>1С · Сталь Мастер</span><span class="status muted">Не подключена</span></div><div class="finance-row"><span>База ФФ и производства</span><span class="status muted">Не подключена</span></div><div class="finance-row"><span>Ozon / Wildberries</span><span class="status muted">Не подключены</span></div><div class="finance-row"><span>Claude</span><span class="status muted">Не подключён</span></div></article><article class="setting">${icon('shield')}<h2>Рабочий режим</h2><p>${config.dataMode==='api'?'Используется серверный адаптер API.':'Демонстрация. Изменения сохраняются только в этом браузере. Это не общая база склада и не система авторизации.'}</p><p>Демо-роль: управляющий. Разграничение доступа и многопользовательская работа будут обеспечиваться сервером.</p>${config.dataMode==='demo'?button('Сбросить демо-данные','reset','',false):''}</article><article class="setting"><h2>Переезд на сервер</h2><p>Экраны используют единый адаптер данных. Серверный контракт и порядок переноса описаны в документации проекта.</p><div class="finance-row"><span>Интерфейс</span><strong>Статический сайт</strong></div><div class="finance-row"><span>Данные</span><strong>${config.dataMode==='api'?'HTTP API':'Демо-хранилище'}</strong></div></article><article class="setting"><h2>Журнал демо-действий</h2><p>Приёмка и перемещения в текущем браузере.</p>${state.audit.slice(0,5).map(a=>`<div class="history"><strong>${e(a.text)}</strong><small>${e(a.actor)}</small></div>`).join('')||'<span class="toolbar-note">Операций пока нет</span>'}</article></div>`;}
function footer(){return `<footer class="bottom-note"><div class="source"><span><i></i>1С: не подключена</span><span><i></i>База ФФ: не подключена</span></div><span>Тестовые данные · демо-срез 03.10.2026 · v0.1</span></footer>`;}
const views={overview,inventory,receiving,places,team,finance,planning,assistant,settings};
function render(){let page=route();if(!pages[page])page='overview';document.title=pages[page][0]+' — Контур склада';
 app.innerHTML=`<div class="shell"><aside class="sidebar" id="sidebar"><a class="brand" href="#/overview"><span class="brand-mark"><i></i><i></i><i></i></span><span><strong>Контур склада</strong><small>WORKSPACE / 01</small></span></a><div class="workspace">${icon('box')}<div><strong>Основной склад</strong><small>3 000 м² · 3 направления</small></div></div><div class="nav-label">РАБОЧЕЕ ПРОСТРАНСТВО</div><nav class="nav" aria-label="Разделы CRM">${Object.entries(pages).filter(([key])=>key!=='settings').map(([key,[name,ico]])=>`<a href="#/${key}" class="${page===key?'active':''}" ${page===key?'aria-current="page"':''}>${icon(ico)}<span>${name}</span>${key==='receiving'?`<span class="nav-count">${state.receipts.filter(r=>r.status==='waiting').length}</span>`:''}</a>`).join('')}</nav><div class="sidebar-foot"><div class="side-note"><strong>Рабочий прототип</strong>Проверяем процессы склада на демонстрационных данных.</div><nav class="nav"><a href="#/settings" class="${page==='settings'?'active':''}">${icon('settings')}Настройки</a></nav><div class="profile space-top"><span class="avatar">ДМ</span><div><strong>Управляющий</strong><small>Демонстрационный доступ</small></div></div></div></aside><div class="main-shell"><header class="topbar"><div class="breadcrumb"><button class="icon-button mobile-menu" data-action="menu" aria-label="Открыть меню">${icon('menu')}</button><span class="crumb-home">Рабочее пространство</span><span class="crumb-home">/</span><span>${pages[page][0]}</span></div><div class="top-right"><span class="demo-badge">ДЕМО-РЕЖИМ</span><a href="#/receiving" class="icon-button" aria-label="Очередь приёмки">${icon('bell')}</a><span class="avatar">ДМ</span></div></header><main id="main">${views[page]()}${footer()}</main></div></div>`;
 if(page==='assistant'){const box=document.querySelector('#messages');box.scrollTop=box.scrollHeight;}
}
function notify(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>el.classList.remove('show'),4000);}
function modal(title,content){lastFocus=document.activeElement;overlay.innerHTML=`<div class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><div class="modal-head"><h2 id="modal-title">${e(title)}</h2><button class="icon-button" data-action="close" aria-label="Закрыть">${icon('close')}</button></div>${content}</section></div>`;document.querySelector('.shell').inert=true;overlay.querySelector('input,select,button')?.focus();}
function closeModal(){overlay.innerHTML='';const shell=document.querySelector('.shell');if(shell)shell.inert=false;lastFocus?.isConnected&&lastFocus.focus();}
function receiveModal(id){const r=state.receipts.find(x=>x.id===id);modal(`Приёмка ${id}`,`<p>${e(r.owner)} · заявлено ${n(r.expected)} шт. Подтверждение увеличит остаток на фактическое количество.</p><form id="receive-form"><input type="hidden" name="id" value="${e(id)}"><label class="field">Фактически принято, шт.<input type="number" name="quantity" min="1" max="100000" step="1" value="${r.expected}" required></label><label class="field">Сотрудник<select name="employeeId">${state.employees.filter(e=>e.direction===r.direction).map(x=>`<option value="${x.id}">${e(x.name)}</option>`).join('')}</select></label><p>Если количество отличается от заявленного, поступление получит статус «Расхождение».</p><div class="form-error" role="alert"></div><div class="modal-actions"><button type="button" class="btn" data-action="close">Отмена</button><button class="btn primary" type="submit">Подтвердить приёмку</button></div></form>`);}
function placeModal(id){const p=state.places.find(x=>x.id===id);modal(id,`<p>${e(p.owner)} · ${p.quantity} шт. · ${e(p.location)}</p><h3>История</h3>${p.history.map(h=>`<div class="history"><strong>${e(h.text)}</strong><small>${e(h.actor)} · ${new Date(h.at).toLocaleString('ru-RU',{timeZone:'Europe/Moscow'})}</small></div>`).join('')}<form id="move-form"><input type="hidden" name="id" value="${e(id)}"><label class="field">Переместить в ячейку<input name="location" placeholder="Например, C-05-02" minlength="2" maxlength="40" required></label><div class="form-error" role="alert"></div><div class="modal-actions"><button type="submit" class="btn primary">Подтвердить перемещение</button></div></form>`);}
function expenseModal(){modal('Новый расход',`<p>Расход будет записан на демо-дату 3 октября 2026 года.</p><form id="expense-form"><label class="field">Статья<select name="category">${['Аренда','Коммунальные услуги','Упаковка','Оборудование','Логистика','Прочее'].map(c=>`<option>${c}</option>`).join('')}</select></label><label class="field">Направление<select name="direction">${directionOptions(filters.direction==='all'?'ff':filters.direction,false)}</select></label><label class="field">Сумма, ₽<input type="number" name="amount" min="0.01" step="0.01" max="100000000" required></label><label class="field">Основание<input name="description" maxlength="200" placeholder="Например, упаковка для отгрузки" required></label><div class="form-error" role="alert"></div><div class="modal-actions"><button class="btn primary" type="submit">Сохранить расход</button></div></form>`);}
function employeeModal(id){const p=payroll(state,filters).find(x=>x.id===id);modal(p.name,`<p>${directions[p.direction]} · ${filters.period==='today'?'3 октября':'27 сентября — 3 октября'}</p><div class="finance-row"><span>Базовая оплата</span><strong>${money(p.base)}</strong></div>${p.rows.map(o=>`<div class="finance-row"><span>${d(o.date)} · ${operationLabels[o.type]}<br><small>${n(o.quantity)} × ${o.rate} ₽ · ${e(o.reference)}</small></span><strong>${money(o.amount)}</strong></div>`).join('')}<div class="finance-row total"><span>Итого начислено</span><span>${money(p.total)}</span></div>`);}
function exportCsv(filename,headers,rows){const csv='\uFEFF'+[headers,...rows].map(row=>row.map(csvCell).join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('CSV выгружен');}
function exportReport(){const m=metrics(state,filters),r=range(filters.period);exportCsv('warehouse-report.csv',['Показатель','Значение','Начало','Конец','Направление'],Object.entries({Начисления:m.revenue,Расходы:m.expenses,Результат:m.profit,Зарплата:m.payroll,Операции:m.operations}).map(([k,v])=>[k,v,r.start,r.end,directions[filters.direction]||'Все']));}
function demoAnswer(text){messages.push({role:'user',text});const m=metrics(state,filters),waiting=filtered(state.receipts).filter(r=>r.status==='waiting');let answer;
 if(/зарплат|сотруд|команд|выработ/i.test(text))answer=`Начислено команде: ${money(m.payroll)}.\nБазовая оплата: ${money(sum(payroll(state,filters),'base'))}. Сдельная часть: ${money(sum(payroll(state,filters),'piece'))}.\nВ расчёт входят только подтверждённые операции. Расшифровка доступна в разделе «Команда и зарплата».`;
 else if(/финанс|прибыл|расход|результат|доход/i.test(text))answer=`Начислено клиентам: ${money(m.revenue)}.\nРасходы с начисленной зарплатой: ${money(m.expenses)}.\nУправленческий результат: ${money(m.profit)}.\nЭто разница начислений и учтённых расходов, не остаток денег. Налоги и часть затрат в демо отсутствуют. Источник: раздел «Финансы».`;
 else if(/при[её]м|ожид|вниман/i.test(text))answer=`Ожидают приёмки: ${waiting.length} поступления, ${sum(waiting,'places')} грузовых мест.\nЗаявлено ${n(sum(waiting,'expected'))} шт.; это ещё не подтверждённый остаток.\n${waiting.length?'Первое поступление в очереди: '+waiting[0].id+'. Откройте «Приёмку» и проверьте фактическое количество.':'Все демо-поступления обработаны.'}`;
 else answer='Этот локальный демо-разбор поддерживает приёмку, зарплату и финансовый результат. Свободный аналитический диалог появится после подключения Claude на сервере.';
 answer+=`\n\nФильтр: ${directions[filters.direction]||'все направления'}, ${filters.period==='today'?'3 октября':'27 сентября — 3 октября'} 2026. Демо-данные с учётом локальных изменений.`;
 messages.push({role:'assistant',text:answer});render();}
document.addEventListener('click',event=>{
 const el=event.target.closest('button,a');if(!el)return;
 if(el.dataset.period){filters.period=el.dataset.period;render();}
 if(el.dataset.receipt){receiptFilter=el.dataset.receipt;render();}
 if(el.dataset.receive)receiveModal(el.dataset.receive);
 if(el.dataset.place)placeModal(el.dataset.place);
 if(el.dataset.employee)employeeModal(el.dataset.employee);
 if(el.dataset.prompt)demoAnswer(el.dataset.prompt);
 const action=el.dataset.action;
 if(action==='close')closeModal();if(action==='menu')document.querySelector('#sidebar').classList.toggle('open');
 if(action==='expense')expenseModal();if(action==='export')exportReport();
 if(action==='inventory-export')exportCsv('warehouse-inventory.csv',['Артикул','Товар','Владелец','Цвет','Размер','Остаток','Резерв','Проверка','Доступно'],filtered(state.products).map(p=>[p.sku,p.name,p.owner,p.color,p.size,p.onHand,p.reserved,p.quarantine,p.onHand-p.reserved-p.quarantine]));
 if(action==='team-export')exportCsv('warehouse-payroll.csv',['Сотрудник','Направление','Количество операций','Часы','База','Сдельно','Всего'],payroll(state,filters).map(p=>[p.name,directions[p.direction],p.quantity,p.hours,p.base,p.piece,p.total]));
 if(action==='reset')modal('Сбросить демо-данные?',`<p>Локальные приёмки, перемещения и расходы будут удалены. Исходный демонстрационный набор восстановится.</p><form id="reset-form"><div class="form-error" role="alert"></div><div class="modal-actions"><button type="button" class="btn" data-action="close">Отмена</button><button class="btn danger" type="submit">Сбросить демо</button></div></form>`);
});
document.addEventListener('change',event=>{if(event.target.id==='direction'){filters.direction=event.target.value;render();}});
document.addEventListener('input',event=>{if(event.target.id==='search'){search=event.target.value;document.querySelector('#search-results').innerHTML=inventoryTable(filtered(state.products).filter(p=>[p.sku,p.name,p.owner,p.color].join(' ').toLowerCase().includes(search.toLowerCase())));}});
document.addEventListener('submit',async event=>{
 event.preventDefault();const form=event.target,formId=form.getAttribute('id'),values=Object.fromEntries(new FormData(form));if(busy)return;
 if(formId==='chat-form'){const text=values.message.trim();if(text)demoAnswer(text);return;}
 if(formId==='forecast-form'){const result=Math.max(0,Math.ceil(Number(values.demand)*Number(values.days)+Number(values.buffer)-Number(values.stock)-Number(values.incoming)));document.querySelector('#forecast-result').innerHTML=`<div class="notice">Рекомендуемое пополнение: <strong>${n(result)} шт.</strong></div>`;return;}
 busy=true;const submit=form.querySelector('[type=submit]');if(submit)submit.disabled=true;
 try{
  if(formId==='receive-form')state=await repo.command('receive',{...values,quantity:Number(values.quantity),requestId:`receive-${values.id}`});
  if(formId==='move-form')state=await repo.command('move',{...values,requestId:crypto.randomUUID()});
  if(formId==='expense-form')state=await repo.command('expense',{...values,amount:Number(values.amount),id:crypto.randomUUID(),requestId:crypto.randomUUID()});
  if(formId==='reset-form'){state=await repo.reset();messages=[];}
  closeModal();render();notify(formId==='reset-form'?'Демо-данные восстановлены':'Изменения сохранены');
 }catch(error){const errorEl=form.querySelector('.form-error');if(errorEl)errorEl.textContent=error.message;else notify(error.message);}finally{busy=false;if(submit)submit.disabled=false;}
});
document.addEventListener('keydown',event=>{
 const dialog=overlay.querySelector('.modal');if(!dialog)return;
 if(event.key==='Escape'&&!busy){closeModal();return;}
 if(event.key==='Tab'){const focusable=[...dialog.querySelectorAll('button,input:not([type=hidden]),select,textarea,a[href]')].filter(x=>!x.disabled),first=focusable[0],last=focusable.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}
});
window.addEventListener('hashchange',()=>{closeModal();search='';render();window.scrollTo(0,0);});
window.addEventListener('storage',async event=>{if(event.key==='warehouse-crm-demo-v1'){try{state=await repo.snapshot();render();}catch(error){notify(error.message);}}});
try{state=await repo.snapshot();render();}catch(error){app.innerHTML=`<div class="error-panel"><h1>Не удалось загрузить данные</h1><p>${e(error.message)}</p><button class="btn" id="retry">Повторить</button>${config.dataMode==='demo'?'<button class="btn danger" id="recovery">Восстановить демо</button>':''}</div>`;document.querySelector('#retry').onclick=()=>location.reload();document.querySelector('#recovery')?.addEventListener('click',async()=>{await repo.reset();location.reload();});}
